### ISSUE TITLE
wrong identation: expected 4 but 2 

### ISSUE THREAD

**Issue by lain0** [lxxxvi/ruboclean#46]
After applying ```ruboclean .rubocop.yml``` 
with:
```yaml
Lint/ConstantDefinitionInBlock:
  Exclude:
    - test/**/*
```
it makes it like:
```yaml
Lint/ConstantDefinitionInBlock:
  Exclude:
  - test/**/*
```
and my yamllint returns 
```error    wrong indentation: expected 4 but found 2  (indentation)```
